<nav aria-label="Page navigation">
    <ul class="pagination">
        <?php if (! isset($pages->previous)) : ?>
            <li class="disabled"><a href="#" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
        <?php else : ?>
            <li><a href="<?= $this->url('default', [
                    'resource' => 'question',
                    'action' => 'index',
                    'id' => $pages->previous,
                    'lang' => $this->current('request')->getAttribute('lang'),
                ]) ?>" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
        <?php endif ?>
        <?php foreach ($pages->pagesInRange as $num) : ?>
            <?php if ($num === $pages->current) : ?>
                <li class="active">
                    <a href="<?= $this->url('default', [
                        'resource' => 'question',
                        'action' => 'index',
                        'id' => $num,
                        'lang' => $this->current('request')->getAttribute('lang'),
                    ]) ?>"><?= $num ?> <span class="sr-only"></span></a></li>
            <?php else : ?>
                <li><a href="<?= $this->url('default', [
                        'resource' => 'question',
                        'action' => 'index',
                        'id' => $num,
                        'lang' => $this->current('request')->getAttribute('lang'),
                    ]) ?>"><?= $num ?></a></li>
            <?php endif ?>
        <?php endforeach ?>
        <?php if (! isset($pages->next)) : ?>
            <li class="disabled"><a href="#" aria-label="Next"><span aria-hidden="true">&raquo;</span></a></li>
        <?php else : ?>
            <li><a href="<?= $this->url('default', [
                    'resource' => 'question',
                    'action' => 'index',
                    'id' => $pages->next,
                    'lang' => $this->current('request')->getAttribute('lang'),
                ]) ?>" aria-label="Next"><span aria-hidden="true">&raquo;</span></a></li>
        <?php endif ?>
    </ul>
</nav>